### ISSUE TITLE
Lab 4.4 Review and Deploy a Project brocken

### ISSUE THREAD

**Issue by rbaumgar** [gpe-mw-training/advanced-process-development-labs#3]
after cloning the repository, review of PolicyQuoteProcess not possible, because it does not exist!
![image](https://user-images.githubusercontent.com/19689547/33989450-d83460ce-e0c7-11e7-9544-bba6a6a5bdba.png)

**Comment by rbaumgar** [comment]
it is only missing in the master and bxms_foundational branches.

**Comment by diego-torres** [comment]
The policyQuoteProcess for the master branch is available in the package: `org.acme.insurance`.
Students should navigate to that package using the `package navigation component` located below the `project selection dropdown`. The `package navigation component` can be toggled with the "Arrow down button" that you see to the right of the `project section dropdown`.
This instruction should be added to any lab instructions including the overview or modification of the policyquote process:
Please let us know of any specific course and lab number so we can modify them. I have detected the following:
  - Advanced Process Development with BPMS6; Lab #5; Step 4.1.3.

**Comment by rbaumgar** [comment]
Diego,

you are right! I found it in the meantime...
I am currently running the
Business Automation Foundations
Lab 4: Process and Rule Execution
https://learning.redhat.com/course/view.php?id=900
